### ISSUE TITLE
Allow configuration of regex "default case"

### ISSUE THREAD

**Issue by ArneSwinnen** [SecurityInnovation/AuthMatrix#52]
The regex now is calculated dynamically based on the response of the initial request, but sometimes it's more useful to have a static regex (e.g. a generic "No permission" message that is present on all authorization-related error pages). 

I would see this as a button at the bottom (e.g. "Regex configuration") where you have (at least) two options: 
- Regex based on status code of original response
- Default static value

Furthermore, a global checkbox whether to invert the regex or not would also be shown in this window. Ideally, upon saving/loading the Authmatrix plugin configuration, this setting would also be taken into account.

**Comment by rsmith31415** [comment]
@ArneSwinnen I suggested the same in [this feature request](https://github.com/SecurityInnovation/AuthMatrix/issues/42#issuecomment-299081162). You can see the response from @mickayz there. Maybe he has figured something out regarding the best way to display the new options.

**Comment by ArneSwinnen** [comment]
@rsmith31415 thanks for the reference. I do hope this feature request will come through indeed, in one way or another. I completely understand the UI can't be too cluttered, but this would be an awesome feature to have. Maybe one "Advanced" button with sub-buttons for these kind of functions?

On another note: @mickayz , where can I donate for this great open-source project? Can't seem to find a way to get in touch with you here on Github. Or should I go via https://www.securityinnovation.com/company/contact-us ?

**Comment by mickayz** [comment]
No need to donate, though I appreciate the consideration :)

I'll look into adding something for this in the next release. My preference right now would be changing the regex field to a list (similar to what's done in the Destinations column in chains) where you can easily add new options and set a default.

**Comment by ArneSwinnen** [comment]
Great to hear, I'll await the next release then! 

Are you sure about not receiving any donations? Even if this feature request doesn't make it in a release, I would be happy to. The plugin has been very useful for me already.

Arne

**Comment by mickayz** [comment]
I've pushed changes in commit c817d58.

The Response Regex field is now a drop-down menu that lists all previously selected regexes, with the ability to type in new ones as well.

If a user wants to change the regex for multiple requests at one time, they can select all relevant requests, right click, select "Change Regexes", and they will be shown a popup allowing them to configure the regexes for these messages using the same dropdown UI as well as a checkbox for Failure Mode.

While this doesn't quite meet the criteria for changing the default regex, it does allow users to update the regexes for each request in one quick and easy step.  I selected this option because I believe it has the best UX for the majority of configurations.

Please let me know if this feature fits your needs (it will be part of the 0.8 release in the coming weeks).  If not, feel free to open the issue once more and we can discuss alternate solutions.

Thank you for the feedback!
-Mick
